name: ci

on:
  push:
    branches:
      - '*'
    branches_ignore:
      - refs/tags/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Make repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's/^cognitant\///')" >> $GITHUB_ENV
      - name: Make branch name
        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's/^refs\/heads\///')" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PWD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            NPM_REGISTRY=${{ secrets.NPM_REGISTRY }}
            NPM_USER=${{ secrets.NPM_USER }}
            NPM_PASS=${{ secrets.NPM_PASS }}
            NPM_EMAIL=${{ secrets.NPM_EMAIL }}
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/library/${{ env.REPO_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKER_REGISTRY }}/library/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }}
            ${{ secrets.DOCKER_REGISTRY }}/library/${{ env.REPO_NAME }}:latest
